export const SHOW_LOGIN_CARD = 'SHOW_LOGIN_CARD'

export const SHOW_SIGNUP_CARD = 'SHOW_SIGNUP_CARD'

export const LOGIN_ERROR_MESSAGE = 'LOGIN_ERROR_MESSAGE'

export const SIGNUP_ERROR_MESSAGE = 'SIGNUP_ERROR_MESSAGE'

export const ATTEMPT_SIGNUP = 'ATTEMPT_SIGNUP'


export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'


export const RECEIVED_SIGNUP_ERROR = 'RECEIVED_SIGNUP_ERROR'


export const RECEIVED_LOGIN_ERROR = 'RECEIVED_LOGIN_ERROR'


export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN'



export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'


export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'



export const LOAD_USER_FROM_LOCAL_STORAGE = 'LOAD_USER_FROM_LOCAL_STORAGE'


export const REQUEST_PROFILE = 'REQUEST_PROFILE'


export const LOGOUT = 'LOGOUT'
